# Global configuration for all applications
# defaults and constants
# default cluster and namespace here is the argocd cluster and namespace

global:
  namespace: cd
  defaultCluster: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true


privateGitRepositories:
  - name: argocd-tooling-applications 
    url: "git@github.com:polarpoint-io/argocd-tooling-applications.git"
  - name: argocd-foundational-applications 
    url: "git@github.com:polarpoint-io/argocd-foundational-applications.git"

publicHelmRepositories:
  - name: argocd-bitnami-repo
    url: "https://charts.bitnami.com/bitnami"
  - name: argocd-crossplane-repo
    url: "https://charts.crossplane.io/stable"
  - name: argocd-dependency-track-repo
    url: "https://evryfs.github.io/helm-charts/"

projects:

      # ApplicationSet generator to apply
      # applications and services to all clusters
      # foundational, security and observational services
    - name: foundational
      urls:
      - name: argocd-foundational-applications 
        url: 'git@github.com:polarpoint-io/argocd-foundational-applications.git'
      - name: argocd-crossplane-repo
        url: "https://charts.crossplane.io/stable"
      - name: argocd-sysdig-falco-repo
        url: "https://falcosecurity.github.io/charts"
      permissions:
          rw:
            description: "Read-Write Access"
            groups:
              - FOUNDATIONAL-RW
          ro:
            description: "Read-Only Access"
            groups:
              - FOUNDATIONAL-RO
      applicationSets:
        destinations:
        - name: deploy
          namespace: '*'
          server: https://kubernetes.default.svc
        applications:
        - name: certmanager
          url: 'git@github.com:polarpoint-io/argocd-foundational-applications.git'
          path: releases/apps/foundational/cert-manager/non-prod
          targetRevision: HEAD
          namespace: foundational
          valuesFile: "values.yaml"
        - name: kuberhealthy
          url: 'git@github.com:polarpoint-io/argocd-foundational-applications.git'
          path: releases/apps/observability/kuberhealthy/non-prod
          targetRevision: HEAD
          namespace: observability
          valuesFile: "values.yaml"

   # applications and services
    - name: tooling
      urls:
      - name: argocd-tooling-applications 
        url: 'git@github.com:polarpoint-io/argocd-tooling-applications.git'
      - name: argocd-crossplane-repo
        url: "https://charts.crossplane.io/stable"
      - name: argocd-dependency-track-repo
        url: "https://evryfs.github.io/helm-charts/"

      permissions:
          rw:
            description: "Read-Write Access"
            groups:
              - TOOLING-RW
          ro:
            description: "Read-Only Access"
            groups:
              - TOOLING-RO
      destinations:
      - name: default
        namespace: '*'
        server: https://kubernetes.default.svc

      applications:
      - name: tooling-argocd-applications
        url: 'git@github.com:polarpoint-io/argocd-tooling-applications.git'
        path: releases
        targetRevision: main
        valuesFile: "values.yaml"
  