argocd:
  ## Argo Configs
  configs:
    params:
      server.insecure: true
    exec.enabled: true # web Terminal active

  controller:
    metrics:
      enabled: true
      applicationLabels:
        enabled: true
      serviceMonitor:
        enabled: true
        namespace: observability

  redis:
    image:
      # -- Redis repository
      repository: redis

  repoServer:
    containerSecurityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile: null
      capabilities:
        drop:
          - ALL
