# Global configuration for all applications
# defaults and constants
# default cluster and namespace here is the argocd cluster and namespace

global:
  namespace: cd
  defaultCluster: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true


privateGitRepositories:
  - name: argocd-tooling-applications 
    url: "https://github.com/polarpoint-io/argocd-tooling-applications.git"


publicHelmRepositories:
  - name: argocd-bitnami-repo
    url: "https://charts.bitnami.com/bitnami"
  - name: argocd-crossplane-repo
    url: "https://charts.crossplane.io/stable"
  - name: argocd-dependency-track-repo
    url: "https://evryfs.github.io/helm-charts/"

projects:
   # applications and services
    - name: tooling
      urls:
      - name: argocd-tooling-applications 
        url: 'git@github.com:pol-onesource/devops-argocd-tooling-applications.git'
      - name: argocd-crossplane-repo
        url: "https://charts.crossplane.io/stable"
      - name: argocd-dependency-track-repo
        url: "https://evryfs.github.io/helm-charts/"

      permissions:
          rw:
            description: "Read-Write Access"
            groups:
              - TOOLING-RW
          ro:
            description: "Read-Only Access"
            groups:
              - TOOLING-RO
      destinations:
      - name: default
        namespace: '*'
        server: https://kubernetes.default.svc

      applications:
      - name: tooling-argocd-applications
        url: 'https://github.com/polarpoint-io/argocd-tooling-applications.git'
        path: releases
        targetRevision: main
        valuesFile: "values.yaml"
  