# Global configuration for all applications
# defaults and constants
# default cluster and namespace here is the argocd cluster and namespace

global:
  namespace: cd
  defaultCluster: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true


privateGitRepositories:
  - name: argocd-tooling-applications 
    url: "git@github.com:polarpoint-io/argocd-tooling-applications.git"
  - name: argocd-foundational-applications 
    url: "git@github.com:polarpoint-io/argocd-foundational-applications.git"
  - name: argo-workflows-library
    url: 'git@github.com:polarpoint-io/argow-template-library.git'

publicHelmRepositories:
  - name: argocd-bitnami-repo
    url: "https://charts.bitnami.com/bitnami"
  - name: argocd-argo-repo
    url: https://argoproj.github.io/argo-helm
  - name: argocd-crossplane-repo
    url: "https://charts.crossplane.io/stable"
  - name: argocd-dependency-track-repo
    url: "https://evryfs.github.io/helm-charts/"
  - name: backstage-repo
    url:  "https://vinzscam.github.io/backstage-chart"
  - name: sonarqube-repo
    url: https://SonarSource.github.io/helm-chart-sonarqube
  - name: jenkins
    url: https://charts.jenkins.io 

projects:

      # ApplicationSet generator to apply
      # applications and services to all clusters
      # foundational, security and observational services
    - name: foundational
      urls:
      - name: argocd-foundational-applications 
        url: 'git@github.com:polarpoint-io/argocd-foundational-applications.git'
      - name: argocd-sysdig-falco-repo
        url: "https://falcosecurity.github.io/charts"
      permissions:
          rw:
            description: "Read-Write Access"
            groups:
              - FOUNDATIONAL-RW
          ro:
            description: "Read-Only Access"
            groups:
              - FOUNDATIONAL-RO
      applicationSets:
        destinations:
        - name: deploy
          namespace: '*'
          server: https://kubernetes.default.svc
        applications:
        - name: prometheus
          url: 'git@github.com:polarpoint-io/argocd-foundational-applications.git'
          path: releases/apps/observability/kube-prometheus-stack
          targetRevision: HEAD
          namespace: observability
          valuesFile: "values.yaml"
        - name: certmanager
          url: 'git@github.com:polarpoint-io/argocd-foundational-applications.git'
          path: releases/apps/foundational/cert-manager
          targetRevision: HEAD
          namespace: foundational
          valuesFile: "values.yaml"
        - name: kuberhealthy
          url: 'git@github.com:polarpoint-io/argocd-foundational-applications.git'
          path: releases/apps/observability/kuberhealthy
          targetRevision: HEAD
          namespace: observability
          valuesFile: "values.yaml"
        - name: linkerd
          url: 'git@github.com:polarpoint-io/argocd-foundational-applications.git'
          path: releases/apps/foundational/linkerd
          targetRevision: HEAD
          namespace: foundational
          valuesFile: "values.yaml"
        - name: falco
          url: 'git@github.com:polarpoint-io/argocd-foundational-applications.git'
          path: releases/apps/security/sysdig-falco
          targetRevision: HEAD
          namespace: security
          valuesFile: "values.yaml"

   # applications and services
    - name: tooling
      urls:
      - name: argocd-tooling-applications
        url: 'git@github.com:polarpoint-io/argocd-tooling-applications.git'
      - name: argocd-crossplane-repo
        url: "https://charts.crossplane.io/stable"
      - name: argocd-dependency-track-repo
        url: "https://evryfs.github.io/helm-charts/"
      - name: backstage-repo
        url:  "https://vinzscam.github.io/backstage-chart"
      - name: argocd-argo-repo
        url: https://argoproj.github.io/argo-helm
      - name: sonarqube-repo
        url: https://SonarSource.github.io/helm-chart-sonarqube
      - name: jenkins
        url: https://charts.jenkins.io
      - name: argo-workflows-library
        url: 'git@github.com:polarpoint-io/argow-template-library.git'
      permissions:
          rw:
            description: "Read-Write Access"
            groups:
              - TOOLING-RW
          ro:
            description: "Read-Only Access"
            groups:
              - TOOLING-RO
      destinations:
      - name: default
        namespace: '*'
        server: https://kubernetes.default.svc

      applications:
      - name: tooling-argocd-applications
        url: 'git@github.com:polarpoint-io/argocd-tooling-applications.git'
        path: releases
        targetRevision: main
        valuesFile: "values.yaml"

# argo workflows template library
      - name: argo-workflows-library
        url: 'git@github.com:polarpoint-io/argow-template-library.git'
        path: releases/apps/workflows
        targetRevision: main
        directory:
          recurseDirectory: true
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
  