{{- range $proj := .Values.projects  }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:  
  name: {{ $proj.name }}
  namespace: {{ $.Values.global.namespace}}
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  {{- range $dest := $proj.destinations }}
  - namespace: '{{ $dest.namespace }}'
    server: {{ $dest.server }}
  {{- end }}
  roles:
  - description: {{ $proj.permissions.rw.description }}
    groups:
    {{- range $permission := $proj.permissions.rw.groups }}
    - {{ $permission }}
    {{- end }}
    name: {{ $proj.name}}-rw
    policies:
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-rw, applications, get, {{ $proj.name}}/*, allow
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-rw, applications, sync, {{ $proj.name}}/*, allow
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-rw, applications, create, {{ $proj.name}}/*, allow
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-rw, applications, update, {{ $proj.name}}/*, allow
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-rw, applications, override, {{ $proj.name}}/*, allow
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-rw, applications, delete, {{ $proj.name}}/*, allow
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-rw, applications, *, {{ $proj.name}}/*, allow

  - description: {{ $proj.permissions.ro.description }}
    groups:
    {{- range $permission := $proj.permissions.ro.groups }}
    - {{ $permission }}
    {{- end }}
    name: {{ $proj.name}}-ro
    policies:
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-ro, applications, get, {{ $proj.name}}/*, allow
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-ro, applications, sync, {{ $proj.name}}/*, deny
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-ro, applications, create, {{ $proj.name}}/*, deny
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-ro, applications, update, {{ $proj.name}}/*, deny
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-ro, applications, override, {{ $proj.name}}/*, deny
    - p, proj:{{ $proj.name}}:{{ $proj.name}}-ro, applications, delete, {{ $proj.name}}/*, deny

  sourceRepos: 
  {{- range $urls := $proj.urls }}
  - {{ $urls.url }}
  {{- end }}

{{- end }}