{{- range $proj := .Values.projects }}
{{- if $proj.applicationSets }}
{{- range $apps := $proj.applicationSets.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $apps.name }}-{{ $proj.name }}
spec:
  generators:
  - list:
      elements:
      {{- range $dest := $proj.applicationSets.destinations }}
      - cluster: {{ $dest.name }}
        url: {{ $dest.server }}
        {{- range $k, $v := $dest.labels }}
        {{ $k }}: {{ $v }}
        {{- end }}
      {{- end }}
  {{- if $apps.labels }}
    selector:
      matchLabels:
        {{- toYaml $apps.labels | nindent 10 }}
  {{- end }}
  template:
    metadata:
      name: >-
        {{printf "{{cluster}}" }}-{{ $apps.name }}
    spec:
      project: {{ $proj.name }}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
      source:
        path: {{ $apps.path }}
        repoURL: {{ $apps.url }}
        targetRevision: {{ .targetRevision }}
    {{- if .directory }}
        directory:
          recurse: {{ .recurseDirectory | default "false" }}
    {{- else }}
        helm:
          valueFiles:
            - {{ .valuesFile | default "values.yaml" }}
      {{- if .parameters }}
          parameters:
            {{- toYaml .parameters | nindent 12 }}
      {{- end }}
    {{- end }}
      destination:
        server: >-
          {{ printf "{{url}}" }}
        namespace: {{ $apps.namespace }}
{{- end }}
{{- end }}
{{- end }}