{{- range $proj := .Values.projects  }}
{{- range $app := $proj.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- if .enableCascade }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}    
  name: {{ $app.name }}
  namespace: {{ $.Values.global.namespace}}
spec:
  source:
    path: {{ $app.path }}
    repoURL: {{ $app.url }}
    targetRevision: {{ .targetRevision }}
{{- if .directory }}
    directory:
      recurse: {{ .recurseDirectory | default "false" }}
{{- else }}
    helm:
      valueFiles:
        - {{ .valuesFile | default "values.yaml" }}
{{- end }}
  project: {{ $proj.name }}          
  destination: 
    server: {{ .targetCluster | default $.Values.global.defaultCluster }}
    namespace: {{ $app.namespace }}
  syncPolicy:
    automated:
{{- if .syncPolicy }}
      selfHeal: {{ .syncPolicy.automated.selfHeal }}  
      prune: {{ .syncPolicy.automated.prune }}
{{- else }}
      selfHeal: {{ $.Values.global.syncPolicy.automated.selfHeal }}  
      prune: {{ $.Values.global.syncPolicy.automated.prune }}
{{- end }}
    syncOptions:
    - CreateNamespace=true
{{- end }}
{{- end }}