{{- range $cluster := .Values.clusters  }}
{{- $localConfig := "{\"bearerToken\":\"\",\"tlsClientConfig\":{\"insecure\":false,\"caData\":\"\"}}" }}
{{- if $cluster.local }}
# Because we use cluster labels for scheduling ApplicationSets, we need to include the cluster running ArgoCD here.
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $cluster.name }}-cluster-secret-local
  namespace: {{ $.Values.global.namespace}}
  labels:
    argocd.argoproj.io/secret-type: "cluster"
    {{- toYaml $cluster.labels | nindent 4 }}
data:
  name: {{ $cluster.name | b64enc }}
  server: {{ $cluster.url | b64enc }}
  config: {{  $localConfig | b64enc  }}
{{- else}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cluster.name }}-cluster-tpl
  namespace: {{ $.Values.global.namespace}}
data:
  name: {{ $cluster.name }}
  server: {{ $cluster.url }}
  config: |
    {
      "bearerToken": "{{`{{.bearerToken | toString}}`}}",
      "tlsClientConfig": {
        "serverName": "{{ $cluster.url }}",
        "ca": "{{`{{.ca | toString}}`}}",
        "insecure": true
      }
    }
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $cluster.name }}-cluster
  namespace: {{ $.Values.global.namespace}}
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ $cluster.name }}-cluster-secret
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: "cluster"
          {{- toYaml $cluster.labels | nindent 10 }}
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: {{ $cluster.name }}-cluster-tpl
          # here you define the keys that should be used as template
          items:
          - key: name
          - key: server
          - key: config

  data:
    - secretKey: bearerToken
      remoteRef:
        key: argocd
        property: argocd-manager-bearer-{{ $cluster.name }}
    - secretKey: ca
      remoteRef:
        key: argocd
        property: argocd-manager-ca-{{ $cluster.name }}

{{- end }}
{{- end }}