{{- range $repo := .Values.privateGitRepositories  }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $repo.name }}-repo-tpl
  namespace: {{ $.Values.global.namespace}}
data:
  url: {{ $repo.url }}
  type: git
  sshPrivateKey: "{{`{{.sshPrivateKey | toString}}`}}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $repo.name }}-private-repo
  namespace: {{ $.Values.global.namespace}}
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster-secrets-store
    kind: ClusterSecretStore
  target:
    name: {{ $repo.name }}-private-repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: "repository"
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: {{ $repo.name }}-repo-tpl
          # here you define the keys that should be used as template
          items:
          - key: url
          - key: type
          - key: sshPrivateKey

  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: github-credentials
        property: github-ssh-access-private-key
{{- end }}