{{- range $repo := .Values.privateHelmRepositories  }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $repo.name }}-tpl
  namespace: {{ $.Values.global.namespace}}
data:
  url: {{ $repo.url }}
  type: helm
  username: "{{`{{.username | toString}}`}}"
  password: "{{`{{.password | toString}}`}}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $repo.name }}-private-repo
  namespace: {{ $.Values.global.namespace}}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secrets-store
    kind: ClusterSecretStore
  target:
    name: {{ $repo.name }}-private-repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: "repository"
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: {{ $repo.name }}-tpl
          # here you define the keys that should be used as template
          items:
          - key: url
          - key: type
          - key: username
          - key: password
  data:
    - secretKey: username
      remoteRef:
        key: argocd
        property: argocd-repository-{{ $repo.name }}-username
    - secretKey: password
      remoteRef:
        key: argocd
        property: argocd-repository-{{ $repo.name }}-token
{{- end }}