{{- range $repo := .Values.privateCredentialsTemplates  }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $repo.name }}-repo-creds-tpl
  namespace: {{ $.Values.global.namespace}}
data:
  name: {{ $repo.name }}
  url: {{ $repo.url }}
  username: "{{`{{.username | toString}}`}}"
  password: "{{`{{.password | toString}}`}}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $repo.name }}-repo-creds
  namespace: {{ $.Values.global.namespace}}
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster-secrets-store
    kind: ClusterSecretStore
  target:
    name: {{ $repo.name }}-repo-creds
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: "repo-creds"
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: {{ $repo.name }}-repo-creds-tpl
          # here you define the keys that should be used as template
          items:
          - key: name
          - key: url
          - key: username
          - key: password

  data:
  - secretKey: username
    remoteRef:
      key: argocd
      property: argocd-repository-{{ $repo.name }}-username
  - secretKey: password
    remoteRef:
      key: argocd
      property: argocd-repository-{{ $repo.name }}-token

{{- end }}