{{- range $repo := .Values.privateCredentialsTemplates  }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $repo.name }}-tpl
  namespace: {{ $.Values.global.namespace}}
data:
  username: "{{`{{.username | toString}}`}}"
  url: {{ $repo.url }}
  password: "{{`{{.password | toString}}`}}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $repo.name }}
  namespace: {{ $.Values.global.namespace}}
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: cluster-secrets-store
    kind: ClusterSecretStore
  target:
    name: {{ $repo.name }}
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: "repo-creds"
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: {{ $repo.name }}-tpl
          # here you define the keys that should be used as template
          items:
          - key: username
          - key: password

  data:
    - secretKey: password
      remoteRef:
        key: service/harbor/chart-user
        property: password
    - secretKey: username
      remoteRef:
        key: service/harbor/chart-user
        property: username

{{- end }}